package com.mccontroler.plan;

import com.mccontroler.MCControler;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Every vanilla recipe, loaded from the table generated by {@code scripts/extract-recipes.ps1}.
 *
 * <p>A Minecraft client is only told about recipes the player has <em>unlocked</em>, so planning
 * purely from the in-game recipe book cannot route through anything undiscovered. This table is
 * extracted from the server jar's own recipe JSON at build time, so it is complete and exactly
 * matches the game version.
 *
 * <p>Tags stay unresolved on disk (e.g. {@code #minecraft:planks}) and are expanded against the
 * live registry, so they pick up whatever the current world actually has.
 */
public final class RecipeTable {

    public enum Kind {
        CRAFT,
        SMELT,
        /** Stonecutter. One block in, one or more out, and usually far cheaper than crafting. */
        CUT,
        /** Smithing table: template + base + addition. The only route to netherite gear. */
        SMITH
    }

    /** One input: any of {@code alternatives} will do, {@code qty} of it needed. */
    public record Input(List<String> alternatives, int qty) {
    }

    /**
     * @param grid smallest crafting grid that fits: 2 (inventory), 3 (crafting table), 0 (furnace)
     */
    public record Recipe(Kind kind, String resultId, int resultCount, int grid, List<Input> inputs) {

        /** True when this needs a crafting table rather than the player's own 2x2 grid. */
        public boolean needsTable() {
            return kind == Kind.CRAFT && grid > 2;
        }
    }

    private static volatile Map<String, List<Recipe>> byResult;
    private static volatile Map<String, List<String>> dropSources;
    private static volatile Map<String, String> naturalBlocks;
    private static volatile Set<String> selfDropping;
    private static volatile Map<String, ToolNeed> toolNeeds;

    private RecipeTable() {
    }

    /** All recipes producing an item, in table order. Never null. */
    public static List<Recipe> producing(String itemId) {
        return table().getOrDefault(itemId, List.of());
    }

    public static int size() {
        return table().size();
    }

    /**
     * Blocks whose loot yields this item, e.g. {@code minecraft:diamond} comes from
     * {@code diamond_ore} and {@code deepslate_diamond_ore}. Recipes alone cannot express this,
     * so without it the planner has no route to ore-drop items. Never null.
     */
    public static List<String> droppedBy(String itemId) {
        return drops().getOrDefault(itemId, List.of());
    }

    /**
     * The dimension a block generates in ({@code overworld}, {@code nether}, {@code end}), or
     * null when it is not naturally generated at all.
     *
     * <p>Having a recipe does not mean crafting is the sensible route. Diorite can be crafted
     * from cobblestone and nether quartz, but it also fills overworld caves — so mining it is
     * obviously right, and planning a trip to the Nether for quartz is obviously wrong. Equally,
     * being a block is not enough: iron blocks and cakes never generate, so they must never be
     * proposed as something to mine.
     */
    public static String naturalDimension(String blockId) {
        return natural().get(blockId);
    }

    public static boolean isNatural(String blockId) {
        return natural().containsKey(blockId);
    }

    /**
     * True when mining this block yields the block itself and nothing else.
     *
     * <p>The distinction matters enormously. Iron ore is naturally generated, but breaking it
     * gives raw iron — so "mine iron ore until you have 9 iron ore" never completes and the bot
     * strips every ore in the area. Only pure self-droppers can be mined to obtain themselves;
     * everything else has to go through {@link #droppedBy}.
     */
    public static boolean dropsSelf(String blockId) {
        return selfDrops().contains(blockId);
    }

    /**
     * What is needed to actually harvest a block.
     *
     * @param tool pickaxe, axe, shovel, hoe, shears, or none
     * @param tier none, stone, iron or diamond — the minimum material that yields drops
     */
    public record ToolNeed(String tool, String tier) {
    }

    /**
     * The tool needed to harvest a block, or null if bare hands will do.
     *
     * <p>Breaking is not harvesting: a stone pickaxe shatters diamond ore for nothing, and a fern
     * vanishes unless shears are held. Without this the planner sends the bot to "mine" things it
     * cannot collect and it stands there destroying them.
     */
    public static ToolNeed toolFor(String blockId) {
        return tools().get(blockId);
    }

    private static Map<String, ToolNeed> tools() {
        Map<String, ToolNeed> local = toolNeeds;
        if (local == null) {
            synchronized (RecipeTable.class) {
                local = toolNeeds;
                if (local == null) {
                    local = new LinkedHashMap<>();
                    try (InputStream in = RecipeTable.class.getResourceAsStream("/tools.tsv")) {
                        if (in == null) {
                            MCControler.LOGGER.error("[MC Controler] tools.tsv missing");
                        } else {
                            try (BufferedReader reader = new BufferedReader(
                                    new InputStreamReader(in, StandardCharsets.UTF_8))) {
                                String line;
                                while ((line = reader.readLine()) != null) {
                                    String[] parts = line.split("\t");
                                    if (parts.length == 3) {
                                        local.put(parts[0], new ToolNeed(parts[1], parts[2]));
                                    }
                                }
                            }
                        }
                    } catch (IOException e) {
                        MCControler.LOGGER.error("[MC Controler] could not read tools.tsv", e);
                    }
                    MCControler.LOGGER.info("[MC Controler] loaded {} tool requirements", local.size());
                    toolNeeds = local;
                }
            }
        }
        return local;
    }

    private static Set<String> selfDrops() {
        Set<String> local = selfDropping;
        if (local == null) {
            synchronized (RecipeTable.class) {
                local = selfDropping;
                if (local == null) {
                    local = new LinkedHashSet<>();
                    try (InputStream in = RecipeTable.class.getResourceAsStream("/selfdrop.tsv")) {
                        if (in == null) {
                            MCControler.LOGGER.error("[MC Controler] selfdrop.tsv missing");
                        } else {
                            try (BufferedReader reader = new BufferedReader(
                                    new InputStreamReader(in, StandardCharsets.UTF_8))) {
                                String line;
                                while ((line = reader.readLine()) != null) {
                                    if (!line.isBlank()) {
                                        local.add(line.trim());
                                    }
                                }
                            }
                        }
                    } catch (IOException e) {
                        MCControler.LOGGER.error("[MC Controler] could not read selfdrop.tsv", e);
                    }
                    MCControler.LOGGER.info("[MC Controler] loaded {} self-dropping blocks",
                            local.size());
                    selfDropping = local;
                }
            }
        }
        return local;
    }

    private static Map<String, String> natural() {
        Map<String, String> local = naturalBlocks;
        if (local == null) {
            synchronized (RecipeTable.class) {
                local = naturalBlocks;
                if (local == null) {
                    local = new LinkedHashMap<>();
                    for (Map.Entry<String, List<String>> e : readPairs("/natural.tsv").entrySet()) {
                        local.put(e.getKey(), e.getValue().get(0));
                    }
                    MCControler.LOGGER.info("[MC Controler] loaded {} naturally generated blocks",
                            local.size());
                    naturalBlocks = local;
                }
            }
        }
        return local;
    }

    /** Reads a {@code key \t comma,separated,values} table from mod resources. */
    private static Map<String, List<String>> readPairs(String resource) {
        Map<String, List<String>> out = new LinkedHashMap<>();
        try (InputStream in = RecipeTable.class.getResourceAsStream(resource)) {
            if (in == null) {
                MCControler.LOGGER.error("[MC Controler] {} missing from the mod jar", resource);
                return out;
            }
            try (BufferedReader reader =
                         new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split("\t");
                    if (parts.length == 2) {
                        out.put(parts[0], List.of(parts[1].split(",")));
                    }
                }
            }
        } catch (IOException e) {
            MCControler.LOGGER.error("[MC Controler] could not read {}", resource, e);
        }
        return out;
    }

    private static Map<String, List<String>> drops() {
        Map<String, List<String>> local = dropSources;
        if (local == null) {
            synchronized (RecipeTable.class) {
                local = dropSources;
                if (local == null) {
                    local = loadDrops();
                    dropSources = local;
                }
            }
        }
        return local;
    }

    private static Map<String, List<String>> loadDrops() {
        Map<String, List<String>> out = new LinkedHashMap<>();
        try (InputStream in = RecipeTable.class.getResourceAsStream("/drops.tsv")) {
            if (in == null) {
                MCControler.LOGGER.error("[MC Controler] drops.tsv missing from the mod jar");
                return out;
            }
            try (BufferedReader reader =
                         new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split("\t");
                    if (parts.length == 2) {
                        out.put(parts[0], List.of(parts[1].split(",")));
                    }
                }
            }
        } catch (IOException e) {
            MCControler.LOGGER.error("[MC Controler] could not read drops.tsv", e);
        }
        MCControler.LOGGER.info("[MC Controler] loaded drop sources for {} items", out.size());
        return out;
    }

    private static Map<String, List<Recipe>> table() {
        Map<String, List<Recipe>> local = byResult;
        if (local == null) {
            synchronized (RecipeTable.class) {
                local = byResult;
                if (local == null) {
                    local = load();
                    byResult = local;
                }
            }
        }
        return local;
    }

    private static Map<String, List<Recipe>> load() {
        Map<String, List<Recipe>> out = new LinkedHashMap<>();
        try (InputStream in = RecipeTable.class.getResourceAsStream("/recipes.tsv")) {
            if (in == null) {
                MCControler.LOGGER.error("[MC Controler] recipes.tsv missing from the mod jar");
                return out;
            }
            try (BufferedReader reader =
                         new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    Recipe recipe = parse(line);
                    if (recipe != null) {
                        out.computeIfAbsent(recipe.resultId(), k -> new ArrayList<>()).add(recipe);
                    }
                }
            }
        } catch (IOException e) {
            MCControler.LOGGER.error("[MC Controler] could not read recipes.tsv", e);
        }
        MCControler.LOGGER.info("[MC Controler] loaded recipes for {} items", out.size());
        return out;
    }

    /** {@code kind \t resultId \t count \t grid \t ing*qty,ing*qty} */
    private static Recipe parse(String line) {
        if (line.isBlank()) {
            return null;
        }
        String[] parts = line.split("\t");
        if (parts.length != 5) {
            return null;
        }
        try {
            Kind kind = switch (parts[0]) {
                case "smelt" -> Kind.SMELT;
                case "cut" -> Kind.CUT;
                case "smith" -> Kind.SMITH;
                default -> Kind.CRAFT;
            };
            int count = Integer.parseInt(parts[2]);
            int grid = Integer.parseInt(parts[3]);

            List<Input> inputs = new ArrayList<>();
            for (String token : parts[4].split(",")) {
                int star = token.lastIndexOf('*');
                if (star < 0) {
                    continue;
                }
                List<String> alternatives = List.of(token.substring(0, star).split("\\|"));
                inputs.add(new Input(alternatives, Integer.parseInt(token.substring(star + 1))));
            }
            if (inputs.isEmpty()) {
                return null;
            }
            return new Recipe(kind, parts[1], count, grid, inputs);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * Expands an input into concrete items, resolving {@code #tag} entries against the live
     * registry. Order is preserved so callers can prefer the first workable option.
     */
    public static List<Item> itemsFor(Input input) {
        List<Item> items = new ArrayList<>();
        for (String alternative : input.alternatives()) {
            if (alternative.startsWith("#")) {
                Identifier id = Identifier.parse(alternative.substring(1));
                TagKey<Item> tag = TagKey.create(Registries.ITEM, id);
                for (Holder<Item> holder : BuiltInRegistries.ITEM.getTagOrEmpty(tag)) {
                    items.add(holder.value());
                }
            } else {
                BuiltInRegistries.ITEM.getOptional(Identifier.parse(alternative)).ifPresent(items::add);
            }
        }
        return items;
    }
}
